name: Code Corruption

on: [push]

permissions:
  contents: write

jobs:
  corrupt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Corrupt Code
        run: |
         FILE="${{ github.workspace }}/.github/workflows/breaking_bad.yml"


          echo "Messing up $FILE..."
          
          # Introduce typos into the workflow file itself
          sed -i 's/runz-on/runs-on/g' "$FILE"
          sed -i 's/name:/naem:/g' "$FILE"
          sed -i 's/permissions:/permisshuns:/g' "$FILE"
          sed -i 's/jobs:/jerbs:/g' "$FILE"

          # Inject chaos comment at the top
          sed -i '1s|^|# 🚨 This workflow is cursed. Fix it if you dare.\n|' "$FILE"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "ChaosOverlord"
          git config --global user.email "chaos@overlord.com"
          git add .
          git commit -m "🔥 Workflow update: This should still work... probably."
          git push || echo "Couldn't push. Maybe GitHub stopped me? 🤔"